language: python
python:
- '3.6'
install:
- make install-dev
script:
- make coverage
deploy:
  provider: pypi
  user: vlttnv
  password:
    secure: G0Eueh2Iv1jXLcEXC8HBGx8kUoVFcglzxqedUuSrHmdTJ/6RvGrmujQrzXlkKUKNtn7TDWlXRd6D35PSA6lfuSx5wbwcwL1V7HPETu0Mu+9eH1QCFBEHp1Awyea0RmpbU9BlPST12msxzSSSnbdWG2T1SlzAd4auiQ27jetYK6vawwN98TETFIHmkXOHWgO9hnp8ByLOoNMRkcrMsVd3Rda6NxZHllldshZ3LbhIQTujJbofhT3AhZB6OExSWOOoxcjhjk4NCHJkg48ppEneYTB+BczQZnqw8SOVKMb7CdH2EYbmdgRJA1R7KDznwUROEonFfXp0b0pmEqeUyKDesqyaPh34sFFlsmWCzq/WbNUtFvG+TSDIMZBfW9NWOPVn+B2rE6CTdcenGP2VkGbnBX5xgnkF508OpSexG/uG/4l1HP8qBMVniWSOcqLuIyDyf19pxbpn7yTUqd+vtpanGQnHVhtb4VzXdP7jnPWZkzGsI7T2EhyKDiP989XQhNDMZBUq/3eunD1jWHgW5Nh80bcGhcbRa87x+B0nylf6Kpc1SG7R9SwN4YDbTkSsr+/fCF+wcEpixpEBUIEgaGIU5NLZcEb0GT+fMS0YDFA+k+CkVxhEOE5qGSWMSs5elki/8DFvRxAqm534kc6pi2LxCWP+7y86Ukdv+MY/jftAqJs=
  on:
    branch: pypi
